#!/usr/bin/env python3
import os
import shutil
import re
from datetime import datetime
from bs4 import BeautifulSoup
from webapp import app, index_with_timestamp


def format_html(html_content):
    try:
        soup = BeautifulSoup(html_content, 'html.parser')
        formatted = soup.prettify()
        return formatted
    except Exception as e:
        print(f"Warning: Could not format HTML: {e}")
        return html_content


def get_current_timestamp_from_html():
    html_path = '../index.html'
    if os.path.exists(html_path):
        try:
            with open(html_path, 'r') as f:
                content = f.read()
                match = re.search(r'<b>Last Updated: </b>([^<]+)', content)
                if match:
                    return match.group(1).strip()
        except Exception as e:
            print(f"Warning: Could not read existing timestamp: {e}")
    return None


def generate_static_html():
    print("Generating static HTML from Flask app...")
    current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S UTC')

    with app.test_client() as client:
        response = client.get('/')

        if response.status_code == 200:
            print("Flask app generated HTML successfully")

            source_html = 'index.html'
            target_html = '../index.html'

            if os.path.exists(source_html):
                if os.path.exists(target_html):
                    old_timestamp = get_current_timestamp_from_html()

                    if old_timestamp:
                        print(f"Previous timestamp: {old_timestamp}")
                        with app.app_context():
                            with app.test_request_context():
                                index_with_timestamp(old_timestamp)

                        with open(source_html, 'r') as f:
                            new_content_old_timestamp = format_html(f.read())

                        with open(target_html, 'r') as f:
                            old_content = f.read()

                        if new_content_old_timestamp == old_content:
                            print(
                                "No pricing data changes detected - keeping existing timestamp")
                            print(f"Timestamp remains: {old_timestamp}")
                            return target_html
                        else:
                            print(
                                "Pricing data changes detected - updating timestamp")
                with app.app_context():
                    with app.test_request_context():
                        index_with_timestamp(current_time)

                with open(source_html, 'r') as f:
                    html_content = f.read()

                formatted_html = format_html(html_content)

                with open(target_html, 'w', encoding='utf-8') as f:
                    f.write(formatted_html)

                print(
                    f"Static HTML formatted and saved to: {os.path.abspath(target_html)}")
                print(
                    f"Generated HTML file size: {len(formatted_html):,} characters")
                print(f"Updated timestamp: {current_time}")
                print(f"Data sorted by: instance type and region for consistent diffs")

                return target_html
            else:
                print("HTML file was not generated by webapp")
                return None
        else:
            print(f"Flask app returned status code: {response.status_code}")
            return None


if __name__ == '__main__':
    generate_static_html()
